# Generated by Django 2.2.9 on 2019-12-30 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_auto_20191228_1704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upvote',
            new_name='Upvoted',
        ),
        migrations.AlterField(
            model_name='comments',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.Ticket'),
        ),
    ]
