# Generated by Django 2.2.9 on 2019-12-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20191230_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvoted',
            old_name='ticket',
            new_name='ticket_voted',
        ),
    ]
